### ISSUE TITLE
tpack doesn't provide all tar procedures

### ISSUE THREAD

**Issue by nat-418** [mittelmark/DGTcl#1]
I have written a program that uses tcllib's tar package, and found that when I tried to build it using tpack that tpack overrides the tar that I included in my app.vfs/lib directory which creates a problem because tpack's tar doesn't include all of the procedures that normal tar does (namely `::tar::contents`) in the `output.tapp` file. I don't understand why this is because I can see that the tpack script includes this procedure.

**Comment by mittelmark** [comment]
Thanks for this bug report, I will try to look into this, may be I have to add a 
package forget tar after the tar file extraction.

Could you try to run a 
catch {
  package forget tar
}
before your own
package require tar

**Comment by nat-418** [comment]
yes that solves the issue

it is probably best if all packages required by tpack do not get inherited by the packed application

**Comment by mittelmark** [comment]
thank you for the report.
I added a package forget tar to allow reloading of the package by the user later (version 0.2.1).

**Comment by nat-418** [comment]
no problem

I am still hesitating between starpack and tpack for my project but now I know tpack will work as expected

closing as resolved
