### ISSUE TITLE
tcl code block should not be evaluated by default

### ISSUE THREAD

**Issue by htopkill** [mittelmark/DGTcl#10]
When i use `pandoc --filter...`  with block code :
\`\`\`tcl  
puts hello
\`\`\`
the code is evaluated and display 'hello'

BUT in markdown,  this syntax is used just for syntax highlighting, not to evaluate a code and display the result of the code. 
You should set 'eval=false' by default

**Comment by mittelmark** [comment]
Thanks for the suggestion. I will do a little bit of research on this. It sound reasonable as Tcl can do nasty things.

**Comment by mittelmark** [comment]
Ok, I might change this default later, for now I implemented the use of environment variable like this in a bash shell like this `export FILTEREVAL=0`  which you can as well reset to 1 afterwards.

Or you might as well change this in the YAML header like this:

---
title: "your title"
author: "your name"
date: 223-XX-XX
tcl:
    eval=0
---

this is then the default chunk option.

The current version could be downloaded as standalone from here:

https://github.com/mittelmark/DGTcl/suites/10511700780/artifacts/521905862 

If you have the time give it a try.

**Comment by mittelmark** [comment]
In the header should be

<pre>
---
title: "your title"
author: "your name"
date: 223-XX-XX
tcl:
    eval=0
---
</pre>

**Comment by mittelmark** [comment]
Here the latest build again, correctly labeled as 0.8.1
https://github.com/mittelmark/DGTcl/releases/download/2023-01-23/pandoc-tcl-filter-0.8.1.zip

Please note, that I am currently moving the project here:

https://github.com/mittelmark/pantcl

Should have almost the same functionality. I thinkl

**Comment by mittelmark** [comment]
This is implemented in the pantcl application see and it seems to work nicely, project https://github.com/mittelmark/pantcl .

Thanks for the report.
