### ISSUE TITLE
Missing utils.tcl in pandoc-tcl-filter.tapp  version 0.8.1

### ISSUE THREAD

**Issue by htopkill** [mittelmark/DGTcl#11]
Display a .dot/graphiz graph works with pandoc-tcl-filter.tapp  V0.7.0 but not V0.8.1
There is a file missing :
pandoc-tcl-filter.vfs/lib/tclfilters/utils.tcl
(https://github.com/mittelmark/DGTcl/releases/download/2023-01-23/pandoc-tcl-filter-0.8.1.zip)

Note: I have regenerate pantcl.bin/pantcl.tapp with your latest pantcl repository (pantcl.bin V0.9.0) and it works.

**Comment by mittelmark** [comment]
I was just adding an release which should fix the utils.tcl issue and as well the @issue in the text.
You could download it here:

https://github.com/mittelmark/DGTcl/releases/download/2023-03-05/pandoc-tcl-filter-0.8.2.zip

Thanks for the bug reports!
