### ISSUE TITLE
When shtmlview opens off-line file.html, it doesn't see file.css

### ISSUE THREAD

**Issue by aplsimple** [mittelmark/DGTcl#4]
Having test.html:

```
    <!DOCTYPE html>
    <html>
    <head>
    <link rel="stylesheet" href="/home/apl/TMP/mkdoc.css">
    </head>
    <body>

    <h2>Testing shtmlview</h2>
    <p>Click: <a href="https://wiki.tcl-lang.org/">Tcl/Tk</a></p>

    </body>
    </html>
```

and running the code:

```
    package require Tk
    package require snit
    lappend auto_path [file dirname [info script]]
    package require shtmlview::shtmlview
    set w [::shtmlview::shtmlview .htm]
    $w browse ~/TMP/test.html
    pack $w -expand 1 -fill both
```

we don't get rendering the page with mkdoc.css
The reason is in **shtmlview**, not in **mkdoc** of course.

**Comment by mittelmark** [comment]
Thanks for the report.

Just to make sure, there is no stylesheet support in this widget, css sections are just ignored, and it is intended only for local HTML files with a basic HTML styling, so your own HTML files, for instance for a help system. I see I have to update the documentation to make this more clear.

**Comment by aplsimple** [comment]
Okay, let it be, however regretfully.
