### ISSUE TITLE
When shtmlview opens off-line file.html, it doesn't run links properly

### ISSUE THREAD

**Issue by aplsimple** [mittelmark/DGTcl#5]
Having test.html:

```
    <!DOCTYPE html>
    <html>
    <head>
    <link rel="stylesheet" href="/home/apl/TMP/mkdoc.css">
    </head>
    <body>

    <h2>Testing shtmlview</h2>
    <p>Click: <a href="https://wiki.tcl-lang.org/">Tcl/Tk</a></p>

    </body>
    </html>
```

and running the code:

```
    package require Tk
    package require snit
    lappend auto_path [file dirname [info script]]
    package require shtmlview::shtmlview
    set w [::shtmlview::shtmlview .htm]
    $w browse ~/TMP/test.html
    pack $w -expand 1 -fill both
```

and clicking the link, we get the error:

![err_link](https://user-images.githubusercontent.com/37333988/153699125-0a8ff6fa-5bf9-4109-bdd7-17caf07038d2.png)

**Comment by mittelmark** [comment]
I am sorry, this is not a web browser. It can be just used for local files. I will try to make the error message and the documentation more clear.

**Comment by aplsimple** [comment]
Thus, would it make sense to disable the hand mouse pointer when hovering a link and do not response to clicking the link?

**Comment by mittelmark** [comment]
I tried to disable http(s) hyperlinks. Look if this works. They should now be just normal text.

**Comment by aplsimple** [comment]
Some links are ignored indeed. But some ones still shows the mentioned error, namely ones with href=# and href="../dir/file.html" and similar.

**Comment by mittelmark** [comment]
Hmm, not sure if I understand this correctly: For me internal links with anchors, relative links starting with dots are as well working. I now just added the possibility to add links like file.html#anchor to a HTML file which is correctly displayed and after loading the file the display is now as well jumping to the anchor, before just the page loaded, but the jump to anchor action was not performed.

```
<h2>Testing shtmlview http(s) links</h2>
    <p>Click: <a href="https://wiki.tcl-lang.org/">Tcl/Tk</a> (not working as expected)  </p>
    <h2>Testing shtmlview internal links </h2>
    <p>Click: <a href="#jump">Jump to target</a> link working</p>
    <h2>Testing shtmlview external/internal links </h2>
    <p>Click: <a href="../dgw/test.html">Jump to file no target</a> link working</p>
    <p>Click: <a href="../dgw/test.html#jump">Jump to file and target</a> link working, jump performed only with the latest checkin</p>
 ```
   
Could you provide some minimal HTML code to show the problem.
Thanks.

**Comment by aplsimple** [comment]
My test is

```
<!DOCTYPE html>
<head><meta charset="UTF-8">
</head>
</html>
<body>
<br>Beginning of html<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>.<br>
<br>The <a href="#">link</a> doesn't work in shtmlview.
<br>The <a href=#>link</a> doesn't work in shtmlview.
<br>It's a link to the beginning of html document (useful when the page has been scrolled down).
<br>End of html
</body>
</html>

```

As for href="../dir/file.html" links, I rechecked them. They work. Sorry.

**Comment by mittelmark** [comment]
Ok, I use HTML since more than 20 years, but did not know the '#' anchor trick ;) I just uploaded a fix for this anchor, that way jumping to the top. Please check it out. Thanks for the bug reports!
