### ISSUE TITLE
scrolling with the mouse wheel

### ISSUE THREAD

**Issue by aplsimple** [mittelmark/DGTcl#7]
The scrolling with the mouse wheel doesn't work, only with the scroll bar and navigating keys.
Why? The wheel is a convenient thing.

**Comment by mittelmark** [comment]
I added a binding for the mouse wheel, on Linux with X this seems to work now. I can't test other systems. I think you must first click into the widget before it can work.

**Comment by aplsimple** [comment]
On Windows, it works even better: no need to click the widget.
Checked in Windows 10 and Windows XP.
