### ISSUE TITLE
Documentation : missing echo in filter-dot documentation

### ISSUE THREAD

**Issue by htopkill** [mittelmark/DGTcl#8]
I test your filter in my application, and the filter-dot documentation do not indicate the 'echo=true/false' to show/hide the code block

( My application,  if you are curious : https://codeberg.org/sudokill/Xwriter.git )
I have already integrate your 'dotcanvas.tcl' as a plugin, and your pandoc filters will appear in the next release. Congrats )

**Comment by mittelmark** [comment]
Thanks for the report, just added this line to the documentation. Nice to see a use of the dotcanvas as well ;)
